* Dohickey
** Development

- ~utop~ should be started from the ~bin~ directory, otherwise it
  attempts to load the ~Js_common~ library and fails because it
  doesn't have compiled javascript support. See ~.ocamlinit-sample~ in
  that directory. Once it's started the buffer ~default-directory~
  will make it accessible (and restart-able) from any file in the
  project.

*** Switches

#+begin_src sh
  opam switch list-available
  opam switch search caml-option
  opam switch set SWITCH
  opam install -y ocaml-manual odig utop user-setup merlin ocamlformat dune dune-release
  odig doc brr
  odig doc ocaml
  odig doc dream # navigate to index
#+end_src

** Design

*** Items

Every action is a ~Dohickey.Item~, totally ordered over the life of
the table by their ~Coda~, which includes a ~Hulc~ timestamp. The
front-end state of the table is determined by applying all of the
items. Items with the same ~Item.key~ may be organized as last writer
wins by timetimestamp, but are also all represented in the history.

~Hulc~ timestamps are a base 64 encoded ~Hlc~ timestamp and a 32 bit
node identifier, build from some host-ish identity (hostname or the
user's name) and some system time stamp. They are opaque, used only
for ordered tie breaking, but must be unique to each host in the
system.

*** Front End

- Front end buttons create ~Request~ messages for the background
  service worker and (usually) make no other change.

- The service worker stores the items in indexeddb, sends them to the
  server for broadcast, and delivers them back to the main client thread.

- The main client thread listens for incoming ~Request~ messages from
  either its own buttons or other users and draws them.

- ~Dims~ ~Request~​s contain just the outer corner of the table,
  ~Draw.sync_rows~ creates all of the cells necessary to fill out the
  dimensions.

- As a convention, cloned ~Domplate~ elements have a ~draw-inert~
  attribute that is removed when the event listeners have been
  attached. We use a querySelector to find inert elements and add the
  listeners only once.

**** Brr instead of sw_of_ocaml

I copied in some code from this [[https://github.com/derui/sw_of_ocaml][sw_of_ocaml]] repo, some of which is
outdated in its types (?). I couldn't get it working and I found a
[[https://ocamlverse.net/content/web_networking.html#ocaml-to-javascript][better list of up to date tools]] which lead me to [[https://github.com/dbuenzli/brr/blob/master/test/test_worker.ml][Brr's worker example]].

** Notes

- No JS in =lib= :: =utop= loads the =lib= directory and all of the
  libraries required to support it. This makes sense for the server,
  but =utop= can't load the =js_of_ocaml= library, it doesn't have
  the JS runtime primitives. Only add those dependencies to the
  =dune= files in the JS specific executable sources.

- Common libraries :: =utop= really only wants to load the stuff in
  =lib=, so the common code is loaded by that, and =lib= implements
  the server. There may be a better way to organize it.
