#!/bin/sh
rate=5
last=0

fswatch src \
        --extended \
        --include '.*\.mli?' \
        --exclude '.*' \
    | while read _event; do
    if [[ $((`date +%s` - last > $rate)) -eq 1 ]]; then
       make
       last=`date +%s`
    fi
done
